language: bash
sudo: true
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
    - luarocks
before_install:
- chmod +x build.sh
- luarocks install --local lpeg
- "`luarocks path`"
script:
- "./build.sh web"
- "./build.sh windows"
- "./build.sh macos"
deploy:
  provider: releases
  skip_cleanup: true
  user: jdrew1303
  file:
  - target/enjoy.love
  - target/enjoy-win.zip
  - target/enjoy-web.zip
  - target/enjoy-macos.zip
  on:
    tags: false
    all_branches: true
  password:
    secure: vF7msHvXlnw0WPaNJyUocgnXtqn4IBCGe3Ens826CiM8Niq2rd58qhuPA4x42EbSFgX0JmjDdxxwU4n6sjsIAVMrzJDOC1QDKkjf5PZGDBBrcFNCrmGq1U4tJfOB4SQrYxOWnwI3TdPl7mN9EzHgo8oBjJLs4SxH0lfSzWKARPpEEzOJ4lgU8JX/ykfo/I5ZNR4H22vVo+HvMX8qXnW3rMsz/wvvkj/zZbArTxtc/GIe0PkqfDtneHOHR1rt4vSAKoUPlWuhB3g3upDEwl5a+eZq4pfeEt+qbTVeMm7kjB13fIM/dcF8JZ22w6do8nJ9cmQnP33Kw5fiCQE7V3wQZ51Dh2eNIZ+a7p7sEr48iJLGJyEerMkBSYPQjkj8PaLP7+3JUD7z3GMaB1LQk6U48Bo4utggaJq92B91sCffNHsjPNddnQTcs3U6Gt2/JvmZdZ+yb10XNed8Y6GGnEl4zMxRxtEgj59TbBNH2n3QLMaG2SF07PIHyunsjf2ZyStqmhqcUA4174ZPXAooOfYixB895euMIcNpx9O6iyvgAYbTp/VPT9KGiOP9KxmGUnuV2EhIIOG4KXxSuShycgzee+YErTfFQxpc0TsjiN0F/R1i0dsQj++barLQ27PVt9b2YVu/9N5Cv08f+A4ma30oKvafvmwUOtkAowpcRz0SCa4=
# after_success:
# - "./build.sh deploy $TRAVIS_REPO_SLUG"
env:
  global: "$GITHUB_TOKEN"
