language: bash
sudo: true
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
    - luarocks
before_install:
- chmod +x build.sh
- luarocks install --local lpeg
- "`luarocks path`"
script:
- "./build.sh web"
- "./build.sh windows"
- "./build.sh macos"
deploy:
  provider: releases
  skip_cleanup: true
  user: jdrew1303
  file:
  - target/enjoy.love
  - target/enjoy-win.zip
  - target/enjoy-web.zip
  - target/enjoy-macos.zip
  on:
    tags: false
    all_branches: true
  password:
    secure: byLxCFyNSXvUA63ayPg9rwNp50FCE4iHTrhWg+GVIgNUzUqmfLqO+aTgnwaGvCLu5LwKL4YVQ/7vVw2cQLHvKPZfkdDn+WjH5B21NcC54sYji8ZuQlo3cXNlEqMc1xM6R3zdW02TM0N3R/UISgRvcW2ivI30gKrABSDhqbKg97cJBHiAvqJwTQHfa446kR1t9kjPIx3NW9wJAbBYxhZ9m+3WP7Q+AXDkzE0vrj0af9yyfCMMc8pmx6YOhYB7Dh4mSs0SvkNHwlveGOxa1lE8BxnvkDoidy4ZBXS+afXN1Vlks7LVJWu+9GucGbwpZnOG055rE5yHH4RcUe+CBq2Z8IcOSVy2ysKJs03Cj667uxcapyli1wBDKPEcGhy1WpnpMyNILfIUwQdsTuOTMUCagEg7v69iWA2AL7+r3TFHsBsmj8/vTOMPKr2+hW4jBiJIbVVDRrTqlk/4oCBwG9ytq0ZQPZGKQwFm2N1tk5+o+hQpbDX5QUCU9ej1WsBC32NkRiByIW5JiQiDrznA1bSTBsETY4H7VPDW4JxtR6lykHJlIgHGp11/NCTPJQsz/C/eWDUF4SyruiTicEc248I2kToDyHW2Nijvobbq9R+MAvQqiLAo9BC4LDUlyGiEtUNB/pwjckUwU3yv86BU4VuL/j5DLQ6WiWQOTkVZe/oSFpQ=
after_success:
- "./build.sh deploy $TRAVIS_REPO_SLUG"
env:
  global: "$GITHUB_TOKEN"
