language: bash
sudo: true
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
    - luarocks
before_install:
- chmod +x build.sh
- luarocks install --local lpeg
- "`luarocks path`"
script:
- "./build.sh web"
- "./build.sh windows"
- "./build.sh macos"
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  file_glob: true
  file: target/dist/*.{love,zip}
  on:
    tags: true
    all_branches: true
  api_key:
    secure: d9mXfXgQ2BLjEZMdLsbLdI1DeE8tC3wOJsFiEIooRvBOZO+UF5g5xUR8JnFCToBVIMYtKJKOLs/H1nNRT7gg0lUHQvBjupWse97RO9CyVNAHGoqtF67y91ru2dlCF+KxpDpZ/1ZSoJHshiqh5GQivwKodIH/63Hkc+okVp0tRwNZlusvPICPWf/MMRLQlL/wo10olWhbFkGOnNBCUuVoOnoOyQ5MyIC7dHkXJ73SG3YHaFnv6FWTqsriwnpZBCuKJxgMkLWrXTy4H7vE6J8ucCxkInRrpqn25/FhnfANPpRwjtlixvhE2VXGQVw/5EI2VhtGrV2yBX8PF9pPRk/Xh0ODDTbonAtN/Ub/RP1rBS6jGGMILg+f1jML0AiT0sFP2FpwTdFcW+88O9jx5pTwN071M5j7tKyX1qFOpE8GvF0m4rpooabFHLY4JDPCMhmfWS6L/suMgsozX3HuiYJ8G6OzEjQdlUteRynfNHBtw0QoDUcM/XYKFqno6/KSIRTT9CeyG8Y3EA/nSZ6tgaaY25nL4EFAUh8SjdT9Ukn9h1jSAxWjXRIwA8nwPhhh3LCMkf3Oxdj39WJK1bY2+dMkmwprNq0LV5ubmWWLXTDJ0VkdwExT2G2V/rOgqtmEGZhSZ5FRE+di2l7bczDq6+BPCwAkv8doeJzcYK8X7xSCKaY=
